name: Integrate conan with CI
on: push
jobs:
  job1:
    name:compile
    runs-on:windows-latest
    steps:
      -name:s1
      run:mkdir build
      -name:s2
      run:cd build
      -name:s3
      run:cmake ../
      -name:s4
      run:cmake --build .